"""Add full_name and rank to registration requests

Revision ID: 60577f1cc98b
Revises: ab7a2c991904
Create Date: 2025-05-03 12:25:02.346139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60577f1cc98b'
down_revision = 'ab7a2c991904'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registration_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('full_name', sa.String(length=150), nullable=False))
        batch_op.add_column(sa.Column('rank', sa.String(length=100), nullable=True))
        batch_op.create_index(batch_op.f('ix_registration_requests_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_registration_requests_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registration_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_registration_requests_status'))
        batch_op.drop_index(batch_op.f('ix_registration_requests_email'))
        batch_op.drop_column('rank')
        batch_op.drop_column('full_name')

    # ### end Alembic commands ###
