"""Add unit_type to Device model, make location non-nullable

Revision ID: 88ae3ea75677
Revises: 60577f1cc98b
Create Date: 2025-05-06 14:01:20.525210

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '88ae3ea75677'
down_revision = '60577f1cc98b'
branch_labels = None
depends_on = None


unit_type_enum = postgresql.ENUM(
    'COMMAND_POST', 'OBSERVATION_POST', 'COMMUNICATION_HUB', 'FIELD_UNIT',
    'LOGISTICS', 'CHECKPOINT', 'MEDICAL', 'TECHNICAL', 'OTHER',
    name='unittype', # <--- Назва типу в PostgreSQL
    create_type=False # Важливо: ми створимо його вручну нижче
)


def upgrade():

    unit_type_enum.create(op.get_bind(), checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unit_type',unit_type_enum, sa.Enum('COMMAND_POST', 'OBSERVATION_POST', 'COMMUNICATION_HUB', 'FIELD_UNIT', 'LOGISTICS', 'CHECKPOINT', 'MEDICAL', 'TECHNICAL', 'OTHER', name='unittype'), server_default='OTHER', nullable=False))
        batch_op.create_index(batch_op.f('ix_devices_unit_type'), ['unit_type'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_devices_unit_type'))
        batch_op.drop_column('unit_type')

    unit_type_enum.drop(op.get_bind(), checkfirst=True)

    # ### end Alembic commands ###
